/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___camer__H
#define ___camer__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__camer(Args *args);

pika_float _camer_cam_count(PikaObj *self, pika_float port);
pika_float _camer_cam_dis_id(PikaObj *self, pika_float port, pika_float obj, pika_float data);
char* _camer_cam_dis_name(PikaObj *self, pika_float port, pika_float obj);
pika_float _camer_cam_dis_obj_id(PikaObj *self, pika_float port, pika_float obj, pika_float data);
char* _camer_cam_dis_obj_name(PikaObj *self, pika_float port, pika_float obj);
void _camer_changer_camer_mode(PikaObj *self, pika_float port, pika_float mode);
void _camer_changer_waite_camer_mode(PikaObj *self, pika_float port, pika_float mode);

#endif
