/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___gray__H
#define ___gray__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__gray(Args *args);

pika_float _gray_cmp_state(PikaObj *self, int port, pika_float num);
void _gray_find_line_init(PikaObj *self);
pika_float _gray_line(PikaObj *self, int port, int line);
pika_float _gray_singe_line_state(PikaObj *self, int port, pika_float num);
pika_float _gray_single_state(PikaObj *self, int port);

#endif
