/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___grayv2__H
#define ___grayv2__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__grayv2(Args *args);

pika_float _grayv2_if_all_ch_way_state(PikaObj *self, int port, int type);
pika_float _grayv2_if_ch_black(PikaObj *self, int port, int ch);
void _grayv2_power_find_if_ch_state(PikaObj *self, int port, pika_float power1, pika_float power2, int ch);
void _grayv2_power_find_line(PikaObj *self, int port, pika_float power);
void _grayv2_power_find_line_encord(PikaObj *self, int port, pika_float power, int encord);
void _grayv2_power_find_line_ms(PikaObj *self, int port, pika_float power, pika_float ms);
void _grayv2_power_find_way_type(PikaObj *self, int port, pika_float power, int type, int enctord);
pika_float _grayv2_read_ch(PikaObj *self, int port, int ch);
void _grayv2_set_ch_rgb(PikaObj *self, int port, int ch1, int ch2, int ch3, int ch4, int ch5, int ch6, int ch7);
void _grayv2_set_find_line_ch(PikaObj *self, int port, int lindex, int mindex, int rindex);
void _grayv2_set_pid(PikaObj *self, int port, pika_float kp, pika_float kd);
void _grayv2_set_rgb(PikaObj *self, int port, int color);
void _grayv2_set_threshold(PikaObj *self, int port, int ch, int value);
void _grayv2_start_calibrate(PikaObj *self, int port);

#endif
