/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___list__H
#define ___list__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__list(Args *args);

void _list_changer_data(PikaObj *self, pika_float index, Arg* data);
pika_float _list_cmp_data(PikaObj *self, char* data);
pika_float _list_data_index(PikaObj *self, char* data);
void _list_delet_all(PikaObj *self);
void _list_delet_index(PikaObj *self, pika_float index);
char* _list_index_data(PikaObj *self, pika_float index);
pika_float _list_num(PikaObj *self);
void _list_pul(PikaObj *self, pika_float index, char* data);
void _list_push(PikaObj *self, Arg* data);

#endif
