/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___message__H
#define ___message__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__message(Args *args);

void _message_FlashMessageBox(PikaObj *self, pika_float num);
void _message_messageInit(PikaObj *self);
void _message_setMessageBox(PikaObj *self, pika_float num);
void _message_setMessageBoxWaite(PikaObj *self, pika_float num);
void _message_waiteMessageBox(PikaObj *self, pika_float num);

#endif
