/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___motor__H
#define ___motor__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__motor(Args *args);

int _motor_absolute_position(PikaObj *self, int port);
int _motor_get_duty_cycle(PikaObj *self, int port);
void _motor_mov(PikaObj *self, char* dir);
void _motor_mov_find_line_init(PikaObj *self);
void _motor_mov_find_line_power_run(PikaObj *self, pika_float left, pika_float right, pika_float power1, pika_float power2, pika_float kp, pika_float kd);
void _motor_mov_find_line_run(PikaObj *self, pika_float left, pika_float right, pika_float power, pika_float kp, pika_float kd);
void _motor_mov_for_degrees(PikaObj *self, char* dir, pika_float degrees, char* velocity);
void _motor_mov_for_power_degrees(PikaObj *self, pika_float duty1, pika_float duty2, pika_float degrees, char* velocity);
void _motor_mov_power(PikaObj *self, pika_float duty1, pika_float duty2, pika_float mode);
void _motor_mov_set_duty(PikaObj *self, pika_float duty);
void _motor_mov_set_power_duty(PikaObj *self, pika_float duty1, pika_float duty2);
void _motor_mov_set_stop_module(PikaObj *self, int module);
void _motor_mov_stop(PikaObj *self);
void _motor_mov_yaw_angle(PikaObj *self, pika_float angle);
void _motor_mov_yaw_line(PikaObj *self, char* dir, pika_float degrees, char* velocity);
void _motor_pair(PikaObj *self, int port1, int port2);
void _motor_pid_pos_ifo(PikaObj *self, int port, pika_float kp, pika_float ki, pika_float kd);
void _motor_pid_speed_info(PikaObj *self, int port, pika_float kp, pika_float ki, pika_float kd);
void _motor_pid_yaw_info(PikaObj *self, pika_float type, pika_float kp, pika_float ki, pika_float kd);
int _motor_relative_angle(PikaObj *self, int port);
void _motor_reset_relative_position(PikaObj *self, int port);
void _motor_run(PikaObj *self, int port, char* dir);
void _motor_run_for_degrees(PikaObj *self, int port, char* dir, pika_float degrees, char* velocity);
void _motor_run_power(PikaObj *self, int port, pika_float duty, pika_float mode);
void _motor_set_accel_limt(PikaObj *self, int port, int limit);
void _motor_set_double_motor_kc(PikaObj *self, pika_float kf);
void _motor_set_duty(PikaObj *self, int port, pika_float duty);
void _motor_stop(PikaObj *self, int port);
void _motor_stop_module(PikaObj *self, int port, int module);

#endif
