/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___music__H
#define ___music__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__music(Args *args);

void _music_setvolumeto(PikaObj *self, int val);
pika_float _music_soundIntensity(PikaObj *self);
void _music_soundPianomusic(PikaObj *self, char* val, pika_float sduty);
void _music_start(PikaObj *self, char* val);
void _music_stop(PikaObj *self);
void _music_untildone(PikaObj *self, char* val);

#endif
