/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___time_struct_time__H
#define ___time_struct_time__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__time_struct_time(Args *args);

int _time_struct_time___getitem__(PikaObj *self, int __key);
Arg* _time_struct_time___iter__(PikaObj *self);
int _time_struct_time___len__(PikaObj *self);
Arg* _time_struct_time___next__(PikaObj *self);
char* _time_struct_time___str__(PikaObj *self);

#endif
