/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib===v1.13.4\r\n");
    pika_platform_printf("_thread===v0.0.7\r\n");
    pika_platform_printf("math===v0.1.1\r\n");
    pika_platform_printf("random===v0.1.4\r\n");
    pika_platform_printf("time===v0.2.2\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import  PikaStdData\n"
            "import  PikaStdLib\n"
            "import  PikaStdTask\n"
            "import  machine\n"
            "import _motor\n"
            "import _thread\n"
            "import _random\n"
            "import _math\n"
            "import _time\n"
            "import _color\n"
            "import _gray\n"
            "import _key\n"
            "import _matrix\n"
            "import _mem\n"
            "import _message\n"
            "import _music\n"
            "import _touch\n"
            "import _ultrasion\n"
            "import _os\n"
            "import _list\n"
            "import _nfc\n"
            "import _camer\n"
            "import _grayv2\n"
            "import newai\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

