#ifndef __PIKA_CONFIG_H
#define __PIKA_CONFIG_H

#define PIKA_FREERTOS_ENABLE 1
#define PIKA_OPTIMIZE PIKA_OPTIMIZE_SIZE
#define PIKA_THREAD_STACK_SIZE 1024
#define PIKA_STACK_BUFF_SIZE   4*1024
#define PIKA_LINE_BUFF_SIZE    128
#define PIKA_DEBUG_ENABLE  0
#define PIKA_ASSERT_ENABLE 0
#define PIKA_THREAD_PRIO 5

#endif
