def cam_count(port:float)->float:...

def changer_camer_mode(port:float,mode:float):...

def changer_waite_camer_mode(port:float,mode:float):...

def cam_dis_obj_id(port:float,obj:float,data:float)->float:...

def cam_dis_obj_name(port:float,obj:float)->str:...

def cam_dis_id(port:float,obj:float,data:float)->float:...

def cam_dis_name(port:float,obj:float)->str:...