def cmp_hsv(port:int,rmin:float,rmax:float,gmin:float,gmax:float,bmin:float,bmax:float)->float:...

def cmp_color(port:int,number:float)->float:...
	
def dectection(port:int)->float:...
	
def rgb(port:int,color:float)->float:...
	
def cmp_lux(port:int,judgment:str,value:float)->float:...
	
def lux(port:int)->float:...
	
def lux_black_line(port:int,value:float)->float:...