def if_ch_black(port:int,ch:int)->float:...

def read_ch(port:int,ch:int)->float:...

def if_all_ch_way_state(port:int,type:int)->float:...

def set_rgb(port:int,color:int):...

def set_ch_rgb(port:int,ch1:int,ch2:int,ch3:int,ch4:int,ch5:int,ch6:int,ch7:int):...

def start_calibrate(port:int):...

def set_threshold(port:int,ch:int,value:int):...

def power_find_way_type(port:int,power:float,type:int,enctord:int):...

def power_find_line_ms(port:int,power:float,ms:float):...

def power_find_line_encord(port:int,power:float,encord:int):...

def power_find_if_ch_state(port:int,power1:float,power2:float,ch:int):...

def power_find_line(port:int,power:float):...

def set_pid(port:int,kp:float,kd:float):...

def set_find_line_ch(port:int,lindex:int,mindex:int,rindex:int):...




