def line(port:int,line:int)->float:...
	
def cmp_state(port:int,num:float)->float:...
	
def single_state(port:int)->float:...
	
def singe_line_state(port:int,num:float)->float:...
	
def find_line_init():...