def delet_index(index:float):...
	
def delet_all():...
	
def pul(index:float,data:str):...
	
def changer_data(index:float, data:any):...
	
def index_data(index:float)->str:...
	
def data_index(data:str)->float:...
	 
def num()->float:...

def cmp_data(data:str)->float:...

def push(self,data:any):...
