def pid_pos_ifo(port:int,kp:float,ki:float,kd:float):...

def pid_speed_info(port:int,kp:float,ki:float,kd:float):...

def pid_yaw_info(type:float,kp:float,ki:float,kd:float):...

def set_double_motor_kc(kf:float):...

def absolute_position(port: int)->int:...

def get_duty_cycle(port: int)->int:...

def relative_angle(port: int)->int:...

def reset_relative_position(port: int):...

def set_accel_limt(port: int,limit:int):...

def run(port:int,dir:str):...

def stop(port:int):...

def stop_module(port:int,module:int):...

def run_for_degrees(port:int,dir:str,degrees:float,velocity:str):...

def run_power(port:int,duty:float,mode:float):...

def set_duty(port:int,duty:float):...

def pair(port1:int,port2:int):...

def mov(dir:str):...

def mov_set_duty(duty:float):...

def mov_for_degrees(dir:str,degrees:float,velocity:str):...

def mov_stop():...

def mov_set_power_duty(duty1:float,duty2:float):...

def mov_set_stop_module(module:int):...

def mov_power(duty1:float,duty2:float,mode:float):...

def mov_for_power_degrees(duty1:float,duty2:float,degrees:float,velocity:str):...

def mov_yaw_line(dir:str,degrees:float,velocity:str):...

def mov_yaw_angle(angle:float):...

def mov_find_line_init():...

def mov_find_line_run(left:float,right:float,power:float,kp:float,kd:float):...

def mov_find_line_power_run(left:float,right:float,power1:float,power2:float,kp:float,kd:float):...